from __future__ import annotations

import numpy as np

def Bc_furutaPendulum(params: np.ndarray) -> np.ndarray:
    """
    function B = Bc_FurutaPendulum(in1)
    %Bc_FurutaPendulum
    %    B = Bc_FurutaPendulum(IN1)

    %    This function was generated by the Symbolic Math Toolbox version 9.1.
    %    11-Jun-2022 09:42:44
    """
    (
      m1,
      m2,
      J,
      jx,
      jy,
      jz,
      L,
      lg,
      Dp,
      Dth,
      gravity,
      a,
    ) = params
    t2 = L**2
    t3 = lg**2
    t4 = J*jx*4.0
    t5 = jx*jz*4.0
    t6 = jx*m1*t2
    t7 = jz*m2*t3*4.0
    t8 = J*m2*t3*4.0
    t9 = jx*m2*t2*4.0
    t10 = m1*m2*t2*t3
    t11 = t4+t5+t6+t7+t8+t9+t10
    t12 = 1.0/t11
    B = np.array([[0.0],[0.0],[a*t12*(jx+m2*t3)*4.0],[L*a*lg*m2*t12*4.0]])
    return B
