from __future__ import annotations

import numpy as np

def Ac_furutaPendulum( params: np.ndarray) -> np.ndarray:
  """
  %Ac_FurutaPendulum
  %    A = Ac_FurutaPendulum(IN1)

  %    This function was generated by the Symbolic Math Toolbox version 9.1.
  %    11-Jun-2022 09:42:44
  """
  (
      m1,
      m2,
      J,
      jx,
      jy,
      jz,
      L,
      lg,
      Dp,
      Dth,
      gravity,
      a,
  ) = params
  t2 = J*4.0
  t3 = L**2
  t4 = jz*4.0
  t5 = lg**2
  t6 = jx*t2
  t7 = jx*t4
  t8 = m1*t3
  t9 = m2*t3*4.0
  t11 = m2*t4*t5
  t12 = m2*t2*t5
  t10 = jx*t8
  t13 = jx*t9
  t14 = m2*t5*t8
  t15 = t2+t4+t8+t9
  t16 = t6+t7+t10+t11+t12+t13+t14
  t17 = 1.0/t16
  A = np.array([[0.0,0.0,1.0,0.0],[0.0,0.0,0.0,1.0],[0.0,L*gravity*m2**2*t5*t17*4.0,Dp*t17*(jx+m2*t5)*-4.0,Dth*L*lg*m2*t17*-4.0][0.0,gravity*lg*m2*t15*t17,Dp*L*lg*m2*t17*-4.0,-Dth*t15*t17]])
  return A
